<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MongoDB\Collection\AbstractCollection'  => __DIR__ . '/src/MongoDB/Collection/AbstractCollection.php',
  'MongoDB\Collection\CollectionInterface' => __DIR__ . '/src/MongoDB/Collection/CollectionInterface.php',
  'MongoDB\Db\AdapterFactory'              => __DIR__ . '/src/MongoDB/Db/AdapterFactory.php',
  'MongoDB\Module'                         => __DIR__ . '/Module.php',
);
