<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaRead\Collection\PizzaCollectionFactory'   => __DIR__ . '/src/PizzaRead/Collection/PizzaCollectionFactory.php',
  'PizzaRead\Collection\ToppingCollectionFactory' => __DIR__ . '/src/PizzaRead/Collection/ToppingCollectionFactory.php',
  'PizzaRead\Collection\PizzaCollection'          => __DIR__ . '/src/PizzaRead/Collection/PizzaCollection.php',
  'PizzaRead\Collection\ToppingCollection'        => __DIR__ . '/src/PizzaRead/Collection/ToppingCollection.php',
  'PizzaRead\Repository\PizzaRepositoryInterface' => __DIR__ . '/src/PizzaRead/Repository/PizzaRepositoryInterface.php',
  'PizzaRead\Repository\PizzaRepositoryFactory'   => __DIR__ . '/src/PizzaRead/Repository/PizzaRepositoryFactory.php',
  'PizzaRead\Repository\PizzaRepository'          => __DIR__ . '/src/PizzaRead/Repository/PizzaRepository.php',
  'PizzaRead\Controller\PizzaControllerFactory'   => __DIR__ . '/src/PizzaRead/Controller/PizzaControllerFactory.php',
  'PizzaRead\Controller\ToppingControllerFactory' => __DIR__ . '/src/PizzaRead/Controller/ToppingControllerFactory.php',
  'PizzaRead\Controller\ToppingController'        => __DIR__ . '/src/PizzaRead/Controller/ToppingController.php',
  'PizzaRead\Controller\PizzaController'          => __DIR__ . '/src/PizzaRead/Controller/PizzaController.php',
  'PizzaRead\Module'                              => __DIR__ . '/Module.php',
);
