<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Module'                     => __DIR__ . '/Module.php',
);
