<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CQRS\Command\CommandInterface'        => __DIR__ . '/src/CQRS/Command/CommandInterface.php',
  'CQRS\Command\CommandResultInterface'  => __DIR__ . '/src/CQRS/Command/CommandResultInterface.php',
  'CQRS\Command\CommandHandlerFactory'   => __DIR__ . '/src/CQRS/Command/CommandHandlerFactory.php',
  'CQRS\Command\CommandHandlerInterface' => __DIR__ . '/src/CQRS/Command/CommandHandlerInterface.php',
  'CQRS\Command\AbstractCommand'         => __DIR__ . '/src/CQRS/Command/AbstractCommand.php',
  'CQRS\Command\CommandHandler'          => __DIR__ . '/src/CQRS/Command/CommandHandler.php',
  'CQRS\Command\CommandResult'           => __DIR__ . '/src/CQRS/Command/CommandResult.php',
  'CQRS\Event\EventHandlerFactory'       => __DIR__ . '/src/CQRS/Event/EventHandlerFactory.php',
  'CQRS\Event\EventHandler'              => __DIR__ . '/src/CQRS/Event/EventHandler.php',
  'CQRS\Module'                          => __DIR__ . '/Module.php',
);
