<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaCli\Collection\PizzaCollectionInterface'   => __DIR__ . '/src/PizzaCli/Collection/PizzaCollectionInterface.php',
  'PizzaCli\Collection\PizzaCollectionFactory'     => __DIR__ . '/src/PizzaCli/Collection/PizzaCollectionFactory.php',
  'PizzaCli\Collection\ToppingCollectionFactory'   => __DIR__ . '/src/PizzaCli/Collection/ToppingCollectionFactory.php',
  'PizzaCli\Collection\PizzaCollection'            => __DIR__ . '/src/PizzaCli/Collection/PizzaCollection.php',
  'PizzaCli\Collection\ToppingCollectionInterface' => __DIR__ . '/src/PizzaCli/Collection/ToppingCollectionInterface.php',
  'PizzaCli\Collection\ToppingCollection'          => __DIR__ . '/src/PizzaCli/Collection/ToppingCollection.php',
  'PizzaCli\Queue\QueueHandler'                    => __DIR__ . '/src/PizzaCli/Queue/QueueHandler.php',
  'PizzaCli\Queue\QueueHandlerInterface'           => __DIR__ . '/src/PizzaCli/Queue/QueueHandlerInterface.php',
  'PizzaCli\Queue\QueueHandlerFactory'             => __DIR__ . '/src/PizzaCli/Queue/QueueHandlerFactory.php',
  'PizzaCli\Repository\PizzaRepositoryInterface'   => __DIR__ . '/src/PizzaCli/Repository/PizzaRepositoryInterface.php',
  'PizzaCli\Repository\PizzaRepositoryFactory'     => __DIR__ . '/src/PizzaCli/Repository/PizzaRepositoryFactory.php',
  'PizzaCli\Repository\PizzaRepository'            => __DIR__ . '/src/PizzaCli/Repository/PizzaRepository.php',
  'PizzaCli\Controller\PizzaControllerFactory'     => __DIR__ . '/src/PizzaCli/Controller/PizzaControllerFactory.php',
  'PizzaCli\Controller\PizzaController'            => __DIR__ . '/src/PizzaCli/Controller/PizzaController.php',
  'PizzaCli\Module'                                => __DIR__ . '/Module.php',
);
