<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PizzaView\Collection\PizzaCollectionFactory'   => __DIR__ . '/src/PizzaView/Collection/PizzaCollectionFactory.php',
  'PizzaView\Collection\ToppingCollectionFactory' => __DIR__ . '/src/PizzaView/Collection/ToppingCollectionFactory.php',
  'PizzaView\Collection\PizzaCollection'          => __DIR__ . '/src/PizzaView/Collection/PizzaCollection.php',
  'PizzaView\Collection\ToppingCollection'        => __DIR__ . '/src/PizzaView/Collection/ToppingCollection.php',
  'PizzaView\Repository\PizzaRepositoryInterface' => __DIR__ . '/src/PizzaView/Repository/PizzaRepositoryInterface.php',
  'PizzaView\Repository\PizzaRepositoryFactory'   => __DIR__ . '/src/PizzaView/Repository/PizzaRepositoryFactory.php',
  'PizzaView\Repository\PizzaRepository'          => __DIR__ . '/src/PizzaView/Repository/PizzaRepository.php',
  'PizzaView\Controller\PizzaControllerFactory'   => __DIR__ . '/src/PizzaView/Controller/PizzaControllerFactory.php',
  'PizzaView\Controller\ToppingControllerFactory' => __DIR__ . '/src/PizzaView/Controller/ToppingControllerFactory.php',
  'PizzaView\Controller\ToppingController'        => __DIR__ . '/src/PizzaView/Controller/ToppingController.php',
  'PizzaView\Controller\PizzaController'          => __DIR__ . '/src/PizzaView/Controller/PizzaController.php',
  'PizzaView\Module'                              => __DIR__ . '/Module.php',
);
